Feature/owner page
MeowSoul/alinaIP pull request #18
Opened 2024-06-17 11:22 UTC by Lx1Cx

2024-06-17 11:22 UTC, Lx1Cx commented
Я потом немного допишу ещё

2024-06-17 17:31 UTC, BlackSoulHub approved these changes

2024-06-18 04:55 UTC, BlackSoulHub requested changes

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/EducationPage/EducationPage.tsx
> +        console.log(courses.getError())
console.log

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/ModalWindow/ModalWindow.tsx
> +        if (password === introducedPassword) {
`inputPassword`, not `introduced`

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/CreateCourse/CreateCourse.tsx
> +            {uploadedFile.length !== 0 &&
simplify:

```ts
uploadedFiles.length && <Components />
```

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/CreateCourse/useCreateCourse.ts
> +                console.log(uploadFileResult.getError())
console.log

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/CreateCourse/useCreateCourse.ts
> +        if (file && file[0]) {
`file[0]` is useless i thing

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/OutputCourse/OutputCourse.tsx
> +        console.log(deleteResult.getError())
console.log

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/OutputCourse/OutputCourse.tsx
> +    window.location.reload()
Use RedirectService

2024-06-18 04:55 UTC, BlackSoulHub commented on src/_pages/OwnerPage/UI/Panel/UI/OutputCourse/OutputCourse.tsx
> +        console.log(courses.getError())
console.log

2024-06-18 05:41 UTC, BlackSoulHub approved these changes

2024-06-18 05:42 UTC, merged