Рабочая версия сайта для пк
MeowSoul/alinaIP pull request #9
Opened 2024-05-08 06:01 UTC by MeowSoul

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/EyeBrowPage/eyeBrowPage.module.css
> +    padding-top: 15vh;
Заменить относительные единицы

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/EyeBrowPage/eyeBrowPage.module.css
> +    flex-direction: column;
flex-direction должен быть после display flex

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/ChooseCourse/ChooseCourseItem/ChooseCourseItem.tsx
> +const ChooseCourseItem: React.FC<ChooseCourseItemProps> = ({ name, url }) => {
Изменить на просто FC без React

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/ChooseCourse/chooseCourse.module.css
> +    width:25%;
Должен быть сверху

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/ProsCourseItem/ProsCourseItem.tsx
> +const ProsCourseItem: React.FC<ProsCourseProps> = ({ numberPros, text }) => {
Изменить на просто FC без React

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/prosCourse.module.css
> +    margin-bottom: 150px;
Объединить margin

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/TableCourse/tableCourse.module.css
> +    display: flex;
Должен быть под padding

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/TableCourse/tableCourse.module.css
> +    display: flex;
Должен быть под padding

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/TableCourse/tableCourse.module.css
> +    display: flex;
Должен быть под padding

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/TableCourse/tableCourse.module.css
> +    display: flex;
Должен быть под padding

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/infoCourse.module.css
> +    margin-top: 50px;
Объединить margin

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/CoursePage/UI/Credit/credit.module.css
> +    display: flex;
Должен быть под padding

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/EducationPage/UI/CoursePreview/CoursePreview.tsx
> +const CoursePreviewItem: React.FC<CoursePreviewItemProps> = ({ name, description, backgroundImage, link }) => {
Убрать React

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/MainPage/MainPage.tsx
> +                <ButtonShadows link={""} text={"ВЫБРАТЬ ОБУЧЕНИЕ"} />
Пустая ссылка

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +    margin: 0 auto;
Поменять местами paddin и margin

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +    padding: 0;
Поменять местами paddin и margin

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/MainPage/UI/buttonShadows/buttonShadows.module.css
> +    padding: 0.75rem 1.25rem;
Должен быть выше

2024-05-08 06:24 UTC, MeowSoul commented on src/_pages/MainPage/UI/buttonShadows/buttonShadows.module.css
> +
Пустой тег

2024-05-09 04:05 UTC, BlackSoulHub commented on src/_pages/EducationPage/UI/CoursePreview/CoursePreview.tsx
> +interface CoursePreviewItemProps {
Maybe `prettier` can fix mistake like this?

2024-05-09 04:05 UTC, BlackSoulHub commented on src/_pages/MainPage/UI/contacts/Contacts.tsx
> +                    <p className={styles.description} onClick={() => setCoordinates([53.614103, 55.946061])}>
Maybe move this to consts?

2024-05-09 04:05 UTC, BlackSoulHub commented on src/сomponents/headerMobile/HeaderMobile.tsx
> +                <Link href={""} className={styles.link}>
Have empty `href`

2024-05-09 04:38 UTC, Lx1Cx requested changes

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/ChooseCourse/ChooseCourseItem/chooseCourseItem.module.css
> +    height: 13vh;
Указание высоты в один момент может не очень приятно сказаться

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/ChooseCourse/chooseCourse.module.css
> +    width:25%;
пробел

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/BlocksCourse/BlocksCourse.tsx
> +                title={"ПЕРВИЧНЫЙ КОНТЕНТ"}
так у тебя просто `""` или `{""}`. Определись и приведи к единому стилю
```tsx
url="/img/content.png"
```

```tsx
title={"ПЕРВИЧНЫЙ КОНТЕНТ"} 
```

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/BlocksCourse/BlocksCourse.tsx
> +                url="/img/promotion.png"
написал выше

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/BlocksCourse/BlocksCourse.tsx
> +                url="/img/treatment.png"
написал выше

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/BlocksCourse/BlocksCourseItem/blocksCourseItem.module.css
> +    height: 10vh;
Про высоту писал выше, но смотри сам чтобы не было проблем которые были с картинками

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/PointsCourse/PointsCourseItem/pointsCourseItem.module.css
> +    background-color:#769BFF;
пробел

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/ProsCourse.tsx
> +const ProsCourse = () => {
Название смущает. Не понятно с ходу что это. Если будешь менять не забудь про `Item` и названия `css`

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/ProsCourseItem/ProsCourseItem.tsx
> +interface ProsCourseProps {
`IProsCourseProps`

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/prosCourse.module.css
> +    margin-top: 50px;
можно убрать и выше прописать `gap`

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/CoursePage/UI/Course/UI/InfoCourse/UI/ProsCourse/prosCourse.module.css
> +    margin-top: 50px;
Чисто предположил

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/UI/CoursePreview/CoursePreview.tsx
> +interface CoursePreviewItemProps {
`ICoursePreviewItemProps` и пробел

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/UI/CoursePreview/coursePreview.module.css
> +    height: 45vh;
Может заменить на проценты

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/UI/CoursePreview/coursePreview.module.css
> +    margin-top: 10vh;
Наверное не очень подходит

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/UI/CoursePreview/coursePreview.module.css
> +    height: 10vh;
про проценты выше писал

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/UI/CoursePreview/coursePreview.module.css
> +        height: 10vh;
выше писал

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/EducationPage/educationPage.module.css
> +    height: 120vh;
про высоту писал. Если норм то просто пропусти

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +    margin: 0 auto 15vh auto;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +    gap: 5vh;
может лучше конкретные значения?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +    margin: 15vh auto;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        width: 60vw;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        width: 40vw;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        width: 30vw;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        width: 40vw;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        width: 35vw;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        padding: 15vh 0;
может лучше конкретные значения?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/aboutMe/aboutMe.module.css
> +        margin: 0 auto 15vh auto;
может лучше процентами?

2024-05-09 04:38 UTC, Lx1Cx commented on src/_pages/MainPage/UI/makeAnAppountment/MakeAnAppointment.tsx
>  const backgroundImage = "/img/lines.png"
Может просто путь передать, а не сохранять в отдельную константу

2024-05-09 04:38 UTC, Lx1Cx commented on src/сomponents/headerMobile/HeaderMobile.tsx
> +                <Link href={""} className={styles.link}>
Have empty `href`

2024-05-09 05:22 UTC, merged